"""
helper utility. converts a JSON that would be a valid input to
browser-pack into a collection of javascript files.
"""
import json
import hashlib
import os, errno

TEMPLATE = """/*
{{
  "id": {id},
  "name": {name},
  "deps": {deps},
  "entry": {entry},
*/
/*
  NOTE: you must update the metadata at the top of this file
  if you add new dependencies. These notes are here to serve
  as a reference in that task.

  DEPENDENCIES (name_used: file_referenced):
  {depstree}


  CALLERS (call_file: name_used):
  {refstree}
  }}
*/
// This was autogenerated from a bundle.

{source}
"""

def derive_name(refs):
  name = "script"
  names = set()
  parents = set()
  for ref in refs.values():
    guess = ref.split('/')[-1].split('.')[0]
    try:
      parguess = ref.split('/')[-2]
    except:
      parguess = '.'
    if '.' not in parguess:
      parents.add(parguess)
    names.add(guess)
  if names:
    name = '-'.join(sorted(names))
  if len(parents) == 1:
    name = "{}/{}".format(list(parents)[0], name)
  else:
    pass
  return name

def write_file(path, source):
  directory = os.path.dirname(path)
  try:
      os.makedirs(directory)
  except OSError as e:
      if e.errno != errno.EEXIST:
          raise
  with open(path, 'a') as f:
    f.write(source)


class FileList():
# id, source, deps, entry
  def __init__(self, path):
    with open(path) as f:
      file_list_raw = json.loads(f.read())
    self.file_list = {f['id']: f for f in file_list_raw}
    self.entry_point = [f for f in file_list_raw if f.get('entry')][0]
    self._add_refs()
    self._name_files()
    self._modify_source()
    print(self.entry_point['id'])

  def _add_refs(self):
    for f_id, f in self.file_list.items():
      f['refs'] = {}
    for f_id, f in self.file_list.items():
      for dep_path, dep_id in f['deps'].items():
        self.file_list[dep_id]['refs'][f_id] = dep_path

  def _name_files(self):
    for f_id, f in self.file_list.items():
      name = derive_name(f['refs'])
      if f.get('entry'):
        name="__ENTRY_POINT"
      md5 = hashlib.md5()
      md5.update(f['source'].encode('utf-8', 'ignore'))
      hash = md5.hexdigest()[-5:]
      f['name'] = "{name}-{id}-{hash}.js".format(
        id=f_id, hash=hash, name=name
      )

  def _modify_source(self):
    for f_if, f in self.file_list.items():
      depstree = {
        f_name: self.file_list.get(f_id, {}).get('name', f_id)
        for f_name, f_id in f['deps'].items()
      }
      refstree = {
        self.file_list.get(f_id, {}).get('name', f_id): ref_name
        for f_id, ref_name in f['refs'].items()
      }
      f['source'] = TEMPLATE.format(
        source=f['source'],
        name=f['name'],
        id=f['id'],
        entry=["false", "true"][f.get('entry', False)],
        deps=json.dumps(f['deps'], indent=None),
        depstree=json.dumps(depstree, indent="    "),
        refstree=json.dumps(refstree, indent="    "),
      )

  def create_files(self, target_folder):
    for meta_f in self.file_list.values():
      file_path = "{}/{}".format(target_folder, meta_f['name'])
      write_file(file_path, meta_f['source'])

if __name__ == '__main__':
  import sys
  fl = FileList(sys.argv[1])
  fl.create_files(sys.argv[2])