"""
given the path of a /src folder generated by _build_source, generates
a prebundle.json that is a valid input to npm's browser-pack utility.
"""

class File():
  def __init__(self, path):
    self._load_file(path)

  def _load_file(self, path):
    pass

if __name__ == '__main__':
  pass